### PR TITLE
Include Globalize logo

### PR DESCRIPTION
**Pull request by rxaviers**
Include Globalize logo on jquery-foundation-logos-eps.zip.

### CODE REVIEW

**Comment by rxaviers** [comment]
Please, what are we waiting for here? Thanks

**Comment by jzaefferer** [comment]
I'll go ahead and merge this.

**Comment by jzaefferer** [comment]
Also updated jquery-wp-content to include the sidebar link and fixed the missing `<hr>`.

**Comment by rxaviers** [comment]
Thanks for spotting and fixing that.

**Pull request closed without merging**
