### PR TITLE
Fixed some broken links

### PR DESCRIPTION
**Pull request by najela**
Hey @arschmitz  I noticed spider reported a redirect error for the url **http://twitter.com/linotype_com** linked from this zip file http://stage.brand.jquery.org/resources/jquery-developer-summit-logos-ai.zip

### CODE REVIEW

**Comment by arschmitz** [comment]
@najela that sounds wrong :-/ would you mind opening an issue on https://github.com/arschmitz/spider.js with any details / links

**Comment by najela** [comment]
@arschmitz Well that's kind of tricky. I'll try to  see if I can recreate the error before I open the issue. It may not be a problem with spider maybe?

**Comment by arthurvr** [comment]
:+1: Thanks!

**Comment by arthurvr** [comment]
Can anyone take care of merging this one? It isn't a content repo.

**Pull request closed without merging**
